### ISSUE TITLE
[Bug] New Graphql query is not active.

### ISSUE THREAD

**Issue by dbadura** [Kong/insomnia#1865] opened 2019-12-23 10:30 UTC
**Describe the bug**
When you add new `grahql` query, you have to click on other and then return to the new one to active it.

**To Reproduce**
1. Create new request and set type to Graphql
2. Write one named query, example:
```graphql
mutation query1 {
  query(id: "ID") {
    id
    name
  }
}
```
3. Click send
4. Add second query
```graphql
mutation query1 {
  query(id: "ID") {
    id
    name
  }
}
```
5. Click send and got following error:
```
{
  "errors": [
    {
      "message": "operation  not found"
    }
  ],
  "data": null
}
```
If you click on the first query/mutation and go back to the second. The second one will be correct and will be processed.

**Expected behavior**
The fresh query/mutation should be ready to use without "deactivating -> activating" flow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - App Version 7.0.6 (7.0.6.3258)

**Additional context**
Video:
https://imgur.com/a/HvSgg71

**Comment by akshitkrnagpal** [comment] 2019-12-23 22:21
Hi 
Looks like it is a duplicate of #1856 which was already fixed.

**Comment by gschier** [comment] 2019-12-30 20:04
Yep it's fixed but not yet released.

**Closed by gschier** 2019-12-30 20:04 UTC
