### ISSUE TITLE
[Bug] Ctrl-D with Sublime key map

### ISSUE THREAD

**Issue by Gabb1995** [Kong/insomnia#685] opened 2018-01-04 09:54 UTC
- Insomnia Version: 5.12.4
- Operating System: Ubuntu 17.04

When using the sublime key map, I use ctrl-d to select multiple instances of the same highlighted text, in insomnia this also creates a duplicate request, can we have it so that when typing inside the body it doesn't do events outside of the text editor key map?

**Comment by jdorleans** [comment] 2018-06-12 02:54
I use Ctrl + D to delete lines on my text editors and I really hate it on insomnia because it duplicates files instead and I'm not use to this behaviour. Is there a way to either change this shortcut by remapping the keys or just disabling it?

**Comment by Gabb1995** [comment] 2018-06-15 14:10
Don't think there is a way to disable it unfortunately.

**Comment by komape** [comment] 2019-12-09 12:11
Deleting a line in the body section with CTRL+D still triggers the creation of a duplicate of the current request.

**Comment by Gabb1995** [comment] 2019-12-09 13:05
Yes I also can confirm this, is there a way now to remove the hotkey?

**Comment by jdorleans** [comment] 2019-12-09 14:54
On the new version, a workaround would be to remap the duplicate behavior **Ctrl + D** to something else. In my particular case, that's a permanent solution.

**Comment by komape** [comment] 2019-12-10 06:59
Isn't it possible to give a shortcut something like a focus. When the user is typing in the body section, only actions for the body section should be taken. If the user is in the request navigation bar, only actions for the navigation bar should be taken.

**Comment by gschier** [comment] 2019-12-11 19:51
It's possible to scope them more finely but I feel like duplication should be an always-available action. I would rather discuss coming up with a less common default combo for duplicate that does not conflict. 

I also agree with @jdorleans that changing the key binding to something else is a good workaround for now. This can be done in the app preferences

**Comment by Gabb1995** [comment] 2019-12-13 08:15
For me I feel it does not make complete sense that if im in the "editor" typing json and I press ctrl + d it makes a duplicate. It should only make a duplicate when my mouse has selected a request from the left menu and I press ctrl + d

**Comment by gschier** [comment] 2019-12-13 21:10
I respectfully disagree but I think what we've revealed is that it's not a clear cut decision. I still feel like making the duplicate hotkey less-likely to conflict is the best middle-ground here.

**Closed** 2021-06-30 23:36 UTC
Labels: C-feature-accepted
