### ISSUE TITLE
[Bug] Multiple windows not prevented on Windows/Linux

### ISSUE THREAD

**Issue by gschier** [Kong/insomnia#1849] opened 2019-12-14 01:08 UTC
See #1763 for original report.

Currently, Insomnia does not support operating in a multi-window environment since database updates are not synchronized between them. We should disable this feature and then properly implement #667 to enable full multi-window support.

**Comment by kreosus** [comment] 2022-08-08 13:01
Closing as a duplicate of https://github.com/Kong/insomnia/issues/667 . This feature is not currently on the roadmap, but hope to add it soon.

**Closed** 2022-08-08 13:01 UTC
Labels: O-linux, O-windows, D-electron, needs-triage
