### ISSUE TITLE
[Bug] Insomnia editor show error when plugin's parametter contain ' or "

### ISSUE THREAD

**Issue by TuyenTk** [Kong/insomnia#1961] opened 2020-02-22 03:33 UTC
**Describe the bug**
Insomnia show error in the editor about cannot parse the [ResponseEval](https://insomnia.rest/plugins/insomnia-plugin-response-eval/) Tag, although when I hover above that tag, I see expected output value, and I can send the request successfully. 

Initially I think the error is from the plugin, but when I see raw request body produced by Insomnia I think the error is caused by the app is not properly escapse the quote/double quote character.

**To Reproduce**
Firstly, install [ResponseEval](https://insomnia.rest/plugins/insomnia-plugin-response-eval/) plugin.

Using Insomnia to get response from following URL: https://jsonplaceholder.typicode.com/todos

![image](https://user-images.githubusercontent.com/4112561/75085379-0c999c80-555b-11ea-9cf3-2b4d3c60a6cb.png)

Then in onther request, I use ResponseEval to get ID of the ToDo item with title **delectus aut autem**:

![image](https://user-images.githubusercontent.com/4112561/75085922-cc3d1d00-5560-11ea-91a1-90c94fab1d44.png)

Parameters:

![image](https://user-images.githubusercontent.com/4112561/75086134-48386480-5563-11ea-80f9-b69d1151c07c.png)

The value in Javascript code field is:

```
`${JSON.parse(output).filter(m => m.title == 'delectus aut autem')[0].id}`
```
Insomnia show this error:

![image](https://user-images.githubusercontent.com/4112561/75085130-b4fa3180-5558-11ea-8f7b-36dd83fd0c57.png)

If I change `'` to `"`:

```
`${JSON.parse(output).filter(m => m.title == "delectus aut autem")[0].id}`
```

I get this error:

![image](https://user-images.githubusercontent.com/4112561/75085157-e4a93980-5558-11ea-96f6-91b3b7d78f27.png)

When I hover above the tag, I see the value `1`, and I can send the request with that value.

Here is raw request body:
```json
{
    "id": "{% ResponseEval 'raw', 'req_6f30ab36c55e4c2babf23fc1f7e509cd', '', '`${JSON.parse(output).filter(m => m.title == \'delectus aut autem\')[0].id}`' %}"
}
```

**Expected behavior**
The error should not appear as the input is in valid state

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Installation Method: download from homepage
 - App Version: v7.1.0

**Additional context**
No

**Comment by gschier** [comment] 2020-02-24 17:16
The ResponseEval plugin should change that parameter to add `encoding: base64` to prevent special characters from causing issues. 

https://github.com/Kong/insomnia/blob/9fe45a8ebb053c5d08ef5aea696dc61e6d11fa8a/plugins/insomnia-plugin-response/index.js#L48

**Comment by jgiovaresco** [comment] 2020-10-23 06:30
@TuyenTk @develohpanda 
It seems the ResponseEval plugin has been updated: https://github.com/taylorgoolsby/insomnia-plugin-response-eval/commit/c21878031708b289a036501bd8e7889a4904c0df

I can't reproduce the issue anymore. We should be able to close this issue.

**Comment by develohpanda** [comment] 2020-11-27 03:09
@jgiovaresco excellent, thank you for validating.

**Closed by develohpanda** 2020-11-27 03:09 UTC
Labels: Plugin System 🔌
