### ISSUE TITLE
[Bug] Unable to restart insomnia

### ISSUE THREAD

**Issue by CerebralFart** [Kong/insomnia#1871] opened 2019-12-31 14:00 UTC
**Describe the bug**
After installing insomnia (7.0.6) via snap, I can start it once, but not a second time. Both via the Ubuntu Dash as well as CLI. It does not show any errors.

**To Reproduce**
1. Install insomnia (`snap install insomnia`)
2. Launch insomnia
3. Close insomnia
4. Launch insomnia again

**Expected behavior**
Being able to restart insomnia

**Screenshots**
I've made a screencapture to demonstrate the problem. See https://youtu.be/YFN9ZGczvOI

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10 64-bit, GNOME 3.34.1
 - Installation Method: snap
 - App Version 7.0.6

**Additional context**
I'm not sure if I've included all required details, feel free to ask me if I forgot anything.

Thanks in advance!

**Comment by gschier** [comment] 2020-01-03 20:09
That's so strange. Can you try that again, and ensure the same binary is being called by typing `which insomnia` before running?

I've just tried the same steps on Ubuntu 18.04 and it launches both times for me.

**Comment by CerebralFart** [comment] 2020-01-03 20:19
Both times it is calling `/snap/bin/insomnia`, see the screenshot below. Sadly I haven't tried other versions as I didn't know about Insomnia back then. 

![Screenshot from 2020-01-03 21-17-49](https://user-images.githubusercontent.com/11133931/71746924-8fad4900-2e6e-11ea-9b09-d2ba7cc30df9.png)

**Comment by gschier** [comment] 2020-01-07 16:57
There have been many problems with the Insomnia snap over the years. Can you try installing the `deb` instead? https://support.insomnia.rest/article/23-installation#ubuntu

**Comment by CerebralFart** [comment] 2020-01-09 09:26
Using `deb` I can launch multiple times, too bad `snap` doesn't work.<br/>
Thanks for the help tho!

**Comment by Zap123** [comment] 2020-08-21 11:21
Same problem for me. It only works the second time if I remove the snap/insomnia folder and start from scratch.
[insomnia-strace.txt](https://github.com/Kong/insomnia/files/5117222/insomnia-strace.txt)

**Comment by black-puppydog** [comment] 2021-04-05 12:44
I stumbled over this issue myself, and found the cause in the [snapcraft forums](https://forum.snapcraft.io/t/some-snaps-will-only-launch-the-first-time/18509/8). The issue for me was that `~/Downloads` was a symlink, not a regular file. I'd expect similar constraints apply to most standard folders, e.g. `~/Music` was mentioned in that thread, too.

**Comment by dimitropoulos** [comment] 2021-04-05 15:33
thanks for the update @black-puppydog.  Gonna close this issue (although not with the intention of shutting down conversation!) since so much has changed re: our snap publishing since this GitHub issue was first created.

**Closed by dimitropoulos** 2021-04-05 15:33 UTC
