### ISSUE TITLE
[Bug] Unable to delete workspace

### ISSUE THREAD

**Issue by billriess** [Kong/insomnia#1867] opened 2019-12-26 16:58 UTC
**Describe the bug**
My team and I are unable to delete a workspace that was transitioned to the "version control beta". We originally created a workspace and shared it as normal but when we heard about the new version control system being added we all enabled that on the workspace. This then lead to a lot of inconsistencies with the workspace not working or updating correctly. So we created a new workspace with the version control on from the start and that one has been great. Now we cannot delete the first (corrupted) workspace. It shows up twice in the "Remote Workspaces" as a pullable item. If we pull and then delete it's still there.

**To Reproduce**
1. Create workspace.
2. Add some history events (add/update/push).
3. Enable version control beta.
4. Add some history events (add/update/push).
5. Disable version control beta. (optional)
6. Attempt to delete workspace.

**Expected behavior**
The workspace gets deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/4182494/71483627-c2a06e80-27d6-11ea-8fe2-f3224e6ca961.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Installation Method: brew
 - App Version: 7.0.6

**Additional context**
I was told to create this ticket by Ukiah Smith of Insomnia Support team.

**Comment by filfreire** [comment] 2022-07-26 09:55
Hi @billriess, thank you for reporting this issue! We're try to go through old and unanswered issues, and would like to apologise on behalf of the team for you not getting a reply in ages 😅 🙇 

Taking into account this was created quite a while ago and we have since done improvement on Insomnia Sync, I will preemptively close this issue.

Please tag me and re-open the issue if you are still having issues with latest [Insomnia version (2022.4.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2). I double checked just in case and I could not reproduce on latest version.

Feel free to report any other issues you come across!

**Closed by filfreire** 2022-07-26 09:55 UTC
Labels: needs-triage
