### ISSUE TITLE
[Improvement] Import Postman all collections

### ISSUE THREAD

**Issue by erikw** [Kong/insomnia#691] opened 2018-01-08 15:25 UTC
- Insomnia Version: 5.12.4 (5.12.4.1752)
- Operating System: macOS 10.13.2 

### 1 
If I export a Postman collection in v2.0 format, it can be imported in Insomnia.
If I export a Postman collection in v2.1 format, Insomnia can't import it and outputs:  "No importers found for file"

### 2

If you come from Postman and want to migrate to Insomnia, it's not feasible to export  individual Postman collections. You want to do 'Postman > Settings > Data > Export data > Download' to make an export of _all_ collections and all environments configured. This should the be imported in Insomnia. Unfortunately there seems to be no support for this right now.

**Comment by gschier** [comment] 2018-01-08 15:26
Correct. I think _Postman > Settings > Data > Export data > Download_ still exports in v1.0 format. Can you confirm this?

**Comment by erikw** [comment] 2018-01-08 15:49
That dump at least start with

```json
 {
         "version": 1,
         "collections": [
                 {

```

so it's version 1 of something :)

**Comment by gschier** [comment] 2018-01-08 16:28
Haha, thanks for that. I started on a more robust Postman importer recently, which will support all versions going forward.

**Comment by program247365** [comment] 2018-01-17 15:24
I ran into this too, you have to find the silly UI button in Postman next to your collection, then it allows you to choose the version:

https://www.getpostman.com/docs/postman/collections/data_formats

Choose version `2.0`, not the other two. Then it works when you import that .json into Insomnia.

Just going to Settings > Data > Export doesn't give you a choice of export version.

**Comment by erikw** [comment] 2018-03-18 16:24
Mr. @stale, don't close this issue as it's of major importance for Insomnia. Postman users will not migrate if then can't bring their environment with them.

**Comment by erikw** [comment] 2018-05-17 20:50
Dear @stale, no recent activity does not make this bug less present. Please disable yourself.

**Comment by gschier** [comment] 2018-05-18 00:50
There, now it won't disable it 👍 😄

**Comment by verglor** [comment] 2018-09-24 18:04
I believe this is duplicate of #682. Or maybe it should be changed to something like "Import bulk of postman collections"

**Comment by gschier** [comment] 2018-09-25 01:14
Ya, I'm not certain but I think Postman's Collection 2.1 format is not the same as the format you get when you export the entire app's data.

**Comment by erikw** [comment] 2019-05-03 13:31
@stale This is not stale, it's still the most major blocker for mass Insomnia adoption for current Postman users. Please un-stale.

**Comment by mwkohler** [comment] 2019-10-03 12:04
Any updates on this @gschier ?

**Comment by fawwaz** [comment] 2019-11-28 09:56
any update ?

**Comment by gschier** [comment] 2019-12-11 20:44
No updates yet but I agree that it is definitely a blocker for adoption.

**Comment by alexdeia** [comment] 2020-08-29 20:39
I try to use Insomnia after Postman, but I have a lot of collections in Postman, and, I'm lazy to move all of them. I hoped this feature will be done.

**Comment by wesleyegberto** [comment] 2020-09-22 06:02
I've created a simple Nodejs script to do that from a Postman backup version 1, it keeps the same structure (currently I have 270+ folders and 740+ requests).

https://gist.github.com/wesleyegberto/8994f8d20b33970ad8304f285e91b0e5

**Comment by mchudinov** [comment] 2021-01-21 20:47
Insomnia proclaims that it supports import from Postman but this is simply not true.
Just now I try to import data from Postman Windows version 7.36 to Insomnia Core 2020.5.2
It does not work.
"_The file does not contain a valid specification_"

**Comment by starlightdreamer** [comment] 2021-05-13 17:28
> Insomnia proclaims that it supports import from Postman but this is simply not true.
> Just now I try to import data from Postman Windows version 7.36 to Insomnia Core 2020.5.2
> It does not work.
> "_The file does not contain a valid specification_"

Similar for me with Mac. I downloaded and tried using Insomnia because it advertised being able to import from Postman. 

Error: No importers found for file
    at module.exports.convert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/index.js:44:9)
    at async importRaw (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:44959:15)
    at async Object.importUri (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:44915:18)
    at async file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:37591:24

Version: Insomnia 2021.3.0
Release date: 4/28/2021
OS: Darwin x64 18.7.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Comment by dimitropoulos** [comment] 2021-05-13 18:07
@starlightdreamer are you able to provide the postman file you are trying to import?  It would help debug what you are experiencing.

**Closed** 2021-06-30 23:36 UTC
Labels: C-feature-accepted
