### ISSUE TITLE
[Bug] Extracting substring to token value doesn't reference tag properly

### ISSUE THREAD

**Issue by ronkot** [Kong/insomnia#1809] opened 2019-11-26 12:18 UTC
I'd need to chain certain requests. In the middle of the chain I'd need to parse a substring from a response JSON field and use that value in the next step. I couldn't find out way to do this. Is it possible somehow?

Example:

Response body

```json
{
  "url": "https://redirect.to?code=abc123"
}
```

And I'd like to extract the `code` query param value from the `$.url` field.

**Comment by gschier** [comment] 2019-11-26 17:55
You'll have to store the response value in a temporary environment variable first.

For example:

```json
{
  "url": "<RESPONSE TAG>",
  "code": "{{ url | replace('https://redirect.to?code=', '') }}"
}
```

Is this for OAuth 2.0? If so, have you tried using Insomnia's built-in OAuth 2.0 support?

**Comment by ronkot** [comment] 2019-11-27 08:53
Thanks @gschier, nice idea 👍 I tried this approach but unfortunately it doesn't work fully. When I create the temporary `code` environment variable in _Manage Environments_, the extracted code value seems ok. But when I use the `code` environment value in a request, the value that gets injected is the original url (not the extracted code). I try to play around more to see if it's just PEBKAC.

> Is this for OAuth 2.0? If so, have you tried using Insomnia's built-in OAuth 2.0 support?

Yes it is. I tried also the built-in OAuth 2.0 flow, but unfortunately it seems that our OAuth flow does not fully follow the standard (shame). Hopefully we'll get that fixed in the future!

**Comment by ronkot** [comment] 2019-11-28 08:14
I tried to debug my configuration but couldn't make it work. Tested that when I change the `url` environment variable to be a string constant everything works as expected. But when I use the response tag method you suggested the `code` environment value that is used in request is plain url value. Looks like the the replace filters are not run for response tags.

Could this be a problem in insomnia?

**Comment by gschier** [comment] 2019-12-04 16:23
Okay, I just reproduce this. Posting a reproducible export here for reference:

```yaml
_type: export
__export_format: 4
__export_date: 2019-12-04T16:21:51.929Z
__export_source: insomnia.desktop.app:v7.0.5
resources:
  - _id: req_b0143e610dab46d0aa03e1432f5d07f3
    authentication: {}
    body:
      mimeType: application/json
      text: |-
        {
        	"code": "https://foo.com?code=123"
        }
    created: 1575475382554
    description: ""
    headers:
      - id: pair_4b04cbadf968438bb2a9562f52d22ed7
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1575475382555
    method: POST
    modified: 1575476270125
    name: Fetch Code
    parameters: []
    parentId: wrk_829e722180014fc48c533233625a5001
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: https://api.insomnia.rest/mock/echo
    _type: request
  - _id: wrk_829e722180014fc48c533233625a5001
    created: 1568746602246
    description: ""
    modified: 1568746602246
    name: Dummy
    parentId: null
    _type: workspace
  - _id: req_d3dc450285624296a8d6bc81b825a556
    authentication: {}
    body: {}
    created: 1575476271209
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1575259926047
    method: POST
    modified: 1575476313784
    name: Use Code
    parameters:
      - description: ""
        id: pair_057a1d50893e40918ce694ad5cc0f526
        name: foo
        value: "{{ code  }}"
    parentId: wrk_829e722180014fc48c533233625a5001
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: https://api.insomnia.rest/mock/echo?code={{code}}
    _type: request
  - _id: env_da3efe009b9bb4d300bac075d1004d6c81fc472e
    color: null
    created: 1568746602281
    data: {}
    dataPropertyOrder: null
    isPrivate: false
    metaSortKey: 1568746602281
    modified: 1568746602281
    name: Base Environment
    parentId: wrk_829e722180014fc48c533233625a5001
    _type: environment
  - _id: env_38af930fb18749cb9ff25eded75c3f40
    color: null
    created: 1575476174748
    data:
      code: "{{ url | replace('https://foo.com?code=', '') }}"
      url: "{% response 'body', 'req_b0143e610dab46d0aa03e1432f5d07f3',
        'b64::JC5jb2Rl::46b', 'never' %}"
    isPrivate: false
    metaSortKey: 1575476174748
    modified: 1575476242447
    name: Testing
    parentId: env_da3efe009b9bb4d300bac075d1004d6c81fc472e
    _type: environment
```

**Comment by develohpanda** [comment] 2019-12-20 10:59
I spent some time investigating this one, and here are my findings. There isn't an issue with how a variable is resolved for a request, there is a more fundamental issue with resolving variables, because I managed to reproduce this bug within the environment variable editor.

If the piped variable is coming from a block using `insomnia-plugin-response`, we see this behavior
```js
{
  "url": "{% response 'body', ... %}", // returns https://redirect.to?code=123
  "code": "{{ url | replace('https://redirect.to?code=', '') }}" // returns 123
  "use-code": "{{ code }}" // returns https://redirect.to?code=123
}
```

And if the piped variable is coming from a regular string, we see this behavior
```js
{
  "url": "https://redirect.to?code=123", // returns https://redirect.to?code=123
  "code": "{{ url | replace('https://redirect.to?code=', '') }}" // returns 123
  "use-code": "{{ code }}" // returns 123
}
```

It seems there is an issue with nunjucks, when nesting `variable <- variable <- block`, while `variable <- variable <- variable` works.

I can see some interesting behavior inside the `templating.render`, when we call the nunjucks renderString method, but I'm going in circles at this point and need to bounce some ideas I think.

https://github.com/Kong/insomnia/blob/e485d55aea4fd2edf09088feeecb4d19a1c75d7f/packages/insomnia-app/app/templating/index.js#L42-L46

**Comment by gschier** [comment] 2019-12-20 20:48
Thanks for taking a look @develohpanda! Seeing your example environments made me remember that this is in the codebase:

https://github.com/Kong/insomnia/blob/f920ba17f2f3ab56bc61f66aaa7b1c599038bf93/packages/insomnia-app/app/common/render.js#L431-L447

Basically, it ensures that variables are rendered before template tags because I figured the most common use case would be to pass a variable into a tag instead of the other way around. In hindsight, my assumption might have been backwards. Either way, sorting either breaks one use case or the other.

But I just had a thought. Now that we have merged your [PR to preserve sort order of environment properties](https://github.com/Kong/insomnia/pull/1497), we probably don't need to sort anymore. We should be able to rely on the user to define variables in preferred render order (top-to-bottom).

**Comment by develohpanda** [comment] 2019-12-21 04:27
Thanks @gschier!

> Either way, sorting either breaks one use case or the other.

I'm concerned about changing the sorting because this is likely to introduce breaking changes, but it is also a fairly specific use case.

I've written a breaking test for this and updated the logic to validate it fixes the behavior, which it does, to an extent. Now, both tag (`{%`) and variable (`{{`) nunjucks are given the same priority, which means if they are run in the user-defined order, they work properly.

The PR around preserving sort-order only kicks in while _rendering_ the keys, and doesn't impact the order in which keys are _processed_ through the rest of the code-base.

While debugging, I set the keys in a particular order, but they are being processed in alphabetical order:
![image](https://user-images.githubusercontent.com/4312346/71302912-f9ad0380-2415-11ea-8c40-9cb23a000152.png)
![image](https://user-images.githubusercontent.com/4312346/71302904-d7b38100-2415-11ea-91e1-6e2243a237e9.png)

But if I rename the keys to ensure they are processed in the correct order, things work.
![image](https://user-images.githubusercontent.com/4312346/71302922-23662a80-2416-11ea-8e6f-93480de19077.png)
![image](https://user-images.githubusercontent.com/4312346/71302928-41338f80-2416-11ea-95c3-0d857324bd01.png)

I have a general idea in which direction to go for fixing this up, but let me know if you have other thoughts, specifically around introducing a potentially breaking change! 😄

**Closed** 2020-03-09 18:20 UTC
Labels: Accepted 👌
