### ISSUE TITLE
[BUG] Insomnia Startup Error

### ISSUE THREAD

**Issue by prameetc** [Kong/insomnia#1743] opened 2019-10-19 06:18 UTC
- Insomnia Version: 7.0.3
- Operating System: MacOS Mojave 10.14.5

## Details

My Insomnia app keeps throwing this error and it does not open. Can someone please help.

<img width="427" alt="Screenshot 2019-10-19 at 11 47 46 AM" src="https://user-images.githubusercontent.com/13821323/67138780-4cc3d800-f266-11e9-8dfb-75b2a53f466f.png">

**Comment by unkownY** [comment] 2019-10-21 06:12
same question,there is no fix for 2 days?

**Comment by muratsplat** [comment] 2019-10-21 08:12
The app couldn't run by this bug. Anyone  know which version is effected ?

**Comment by muratsplat** [comment] 2019-10-21 08:16
I have installed Insomnia-7.0.3 version. The problem is resolved It seems

**Comment by mg-code** [comment] 2019-10-21 08:41
Same here. Updating to 7.0.3 version solved problem.

**Comment by wsajosh** [comment] 2019-10-25 10:54
Same issue here. Fixed by updating to 7.0.3

**Comment by prameetc** [comment] 2019-10-28 06:49
I still get the same error after updating to 7.0.3

**Comment by Bosbaba** [comment] 2019-11-01 11:03
FYI I just fixed this on my mac. Can't tell you why this happened but this is how I fixed it.
In my case it looks like the `php5` directory was moved or something. If you look in `/usr/local/` my `php5` was in `php5-5.6.19-20160310-141555` so I just created a `php5` symlink to `php5-5.6.19-20160310-141555` i.e. `ln -s php5-5.6.19-20160310-141555 php5`

**Comment by emanueledona** [comment] 2019-11-07 15:14
Today i try to reinstall via brew without any success, you can find my configuration at [#1754 ](https://github.com/getinsomnia/insomnia/issues/1754)

**Comment by benholz** [comment] 2020-03-14 00:57
Well, after encountering this error and almost giving up, I ended up getting this working. What I think was happening is that I had php5 libraries in my /usr/local/lib directory. I had just migrated over to a new machine so PHP v7.4 was already installed in /usr/bin so all I had to do was run: `brew link --overwrite php ` and now Insomnia works! Excellent!

**Comment by filfreire** [comment] 2022-08-12 11:33
Hi folks, I'm going to go ahead and close this one since it's been a while, but feel free to report a new issue if you are still getting this error in one of our [latest Insomnia versions](https://github.com/Kong/insomnia/releases)

**Closed by filfreire** 2022-08-12 11:33 UTC
Labels: needs-triage
