### ISSUE TITLE
[Bug] base_url not correctly interpreted for swagger

### ISSUE THREAD

**Issue by Azef1** [Kong/insomnia#1006] opened 2018-06-25 20:02 UTC
- Insomnia Version: 5.16.6
- Operating System: Win10 x64

## The problem
The variable "base_url" is not correctly interpreted. The correct url will be http://petstore.swagger.io/v2/
![image](https://user-images.githubusercontent.com/15362041/41872431-24cd8d06-78c2-11e8-887b-887f0d5efd48.png)

## How to reproduce the problem

1. Import this definition swagger: https://petstore.swagger.io/v2/swagger.json 

## Details
You can see in https://petstore.swagger.io/v2/swagger.json :

- scheme variable doesn't exist in json file but scheme**s** exist in json file
- host exist, so why Insomnia doesn't find value ?
- base_path doesn't exist in json file but basePath exist in json file

Do you know if Insomnia support "Swagger" correctly ?

**Comment by gschier** [comment] 2018-08-27 20:37
A community contribution for this would be awesome! I know absolutely nothing about Swagger.

**Comment by thewheat** [comment] 2018-10-03 14:05
I had a look at this and I think the problem is that no environment was selected. 

- See the left side of your screenshot that I've highlighted below where there is a `No environment` warning
![image](https://user-images.githubusercontent.com/892961/46415353-a9d21600-c757-11e8-85b1-2a39b2294f40.png)
- If you select the environments dropdown and pick `Use Swagger env`, you should be able to make successful calls 😄 
![image](https://user-images.githubusercontent.com/892961/46415324-9cb52700-c757-11e8-9979-5b4642cf4567.png)
- The base environment specifies `base_url`
![image](https://user-images.githubusercontent.com/892961/46415010-f406c780-c756-11e8-8242-2ef0da3bd112.png)
- And is built up based on the values in `Swagger env`
![image](https://user-images.githubusercontent.com/892961/46414999-ef421380-c756-11e8-9f92-cf6427cdbaf7.png)

So I think the import works correctly but the confusion came from not knowing to select the environment. 
- Maybe this issue could be repurposed so that when a workspace is created and there is a single environment, that the environment be selected by default?

**Comment by thewheat** [comment] 2020-10-04 14:56
I believe this can now be closed as importing auto selects the newly created environment 👍
![image](https://user-images.githubusercontent.com/892961/95018859-c7168380-0694-11eb-98c7-4862529e51b3.png)

**Closed** 2020-10-17 21:27 UTC
Labels: Accepted 👌, Good First Issue, Help Wanted
