### ISSUE TITLE
Response preview: right-click a value to create/save a variable

### ISSUE THREAD

**Issue by arturhun** [Kong/insomnia#1834] opened 2019-12-10 16:48 UTC
- Insomnia Version: 7.0.5
- Operating System: 10.15.1 Catalina

## Details

I would like to be able to right-click a value in Preview pane

![image](https://user-images.githubusercontent.com/42932011/70549865-30ad2a80-1b75-11ea-9288-92aa43b6c2e0.png)

and save it as a variable - either new, or update the existing one.

In the above example I would update my `accessToken` variable after the token expires, and thus it would take me just one click to have all my acess tokens throughout all calls, updated.

**Comment by gschier** [comment] 2019-12-11 16:25
Thanks for the suggestion! Going to close this as a Duplicate of #1796 so we can continue the discussion in one place.

**Comment by gschier** [comment] 2019-12-11 16:26
Duplicate of #1796

**Closed** 2019-12-11 16:27 UTC
Labels: Duplicate
